### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by AInoob** [hustcc/timeago-react#14]
Uncaught Error: Module build failed: ReferenceError: Unknown plugin "transform-es3-member-expression-literals" specified in "*/node_modules/timeago-react/.babelrc" at 0, attempted to resolve relative to "*/node_modules/timeago-react"
    at */node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17

npm install babel-plugin-transform-es3-member-expression-literals will solve the problem

**Comment by hustcc** [comment]
Maybe, can help to send a pr?

**Comment by AInoob** [comment]
Turns out it's a common mistake, https://github.com/styleguidist/react-styleguidist/issues/454 .
