### ISSUE TITLE
Using TimeAgo within code and outside render method

### ISSUE THREAD

**Issue by Mike-tech** [hustcc/timeago-react#17]
This is a question rather than issue. 

I really love this plugin and work great. But i would also love to use this module outside the render method. So this my scenario, i'm using time ago during my initial page load, so inside the render method i have something like this:

`<TimeAgo datetime={item.createdAt} title={new Date(item.createdAt.toString()).toLocalString('en-GB)} />`

Above is used as part of an items collection and works great with no problem. Now each item is being updated via ajax. After a successful callback of the update i would like to update the TimeAgo on the dom via code on the fly, without reloading the whole component on the screen. I am trying something like this using reactElementToJSXString:

`
const divCreated = document.getElementById('someId') as HTMLDivElement;
if(divCreated !== null) {
 divCreated.innertHTML = reactElementToJSXString(<TimeAgo datetime={item.createdAt} title={new Date(item.createdAt.toString()).toLocalString('en-GB)} />)
}
`
While the above compiles, it just print the TimeAgo as html to the screen and its not processed by the plugin and converts to into readable friendly time.

My question is there a way to do this within a normal method? If not any alternative module that support what i'm trying to do. Almost all example i've seen are module component which works fine in render method not dynamically. 

Thanks

**Comment by hustcc** [comment]
You can set the date into state after the ajax callback.

and use the date in state.

**Comment by Mike-tech** [comment]
@hustcc  yes, i was able to create a placeholder div and set it's jsx content via state and retrieve its value after ajax callback. Works a treat.
I often use this method and not sure why i didn't think of trying this with TimeAgo initially. 

Many thanks
