### ISSUE TITLE
Requesting to change or add the feature to show 'a few second ago'

### ISSUE THREAD

**Issue by pritam3010** [hustcc/timeago-react#18]
This is a request not an issue.
It looks weird to me that plugin showing an increasing "... second ago"  text after 10 second.
Could you please change or add the feature so that it can show 'a few second ago' or something like this instead of increasing second counter.
Sorry for my English.

**Comment by hustcc** [comment]
@pritam3010 you can register your own locales. ref readme: https://github.com/hustcc/timeago.js
