### ISSUE TITLE
TimeAgo-react not using locale translated in timeago repo

### ISSUE THREAD

**Issue by Nihaux** [hustcc/timeago-react#2]
Hello,
apparently the timeago-react is unable to find locales that are translated in the timeago repo
`<TimeAgo datetime={article.createdAt} locale='zh_CN' />`
works but all other languages:
```
<TimeAgo datetime={article.createdAt} locale='ar' />
<TimeAgo datetime={article.createdAt} locale='fr' />
```
fallback to english default.

Am i doing sth wrong ?

**Comment by hustcc** [comment]
This library has not achieve the `register` of `timeago.js`.

Next version, I will add it, if you have some ideal, welcome to PR.

**Comment by hustcc** [comment]
**v1.0.7@npm** can support locale like `ar`, `fr`.

all locales [here](https://github.com/hustcc/timeago.js/issues/19) are supported.

**Comment by Nihaux** [comment]
Thank you ! 👍

**Comment by y1n0** [comment]
Hello, the locales are still not working. even in the demo page. I tried to change the locale in React dev tools and it turned out it only works with `vi`
