### ISSUE TITLE
'opts.minInterval' unit (seconds/millseconds etc) is not mentioned in documentation

### ISSUE THREAD

**Issue by palerdot** [hustcc/timeago-react#30]
As mentioned, documentation does not say what is the unit for `opts.minInterval`. I think it is number in `seconds` (arrived at this after trial and error). That is `60` will update every minute. I think this information should be mentioned in documentation.

**Comment by alanwei0** [comment]
Done. Thanks for your suggestion. https://github.com/hustcc/timeago-react/commit/387a047d9df19205ce9a000de0f5ffcd70a4b92b here.
