### ISSUE TITLE
How do you use the options?

### ISSUE THREAD

**Issue by 6ichem** [hustcc/timeago-react#36]
The opts minInterval and relativeDate are marked down as props in the documentation but there's no way to show how it's supposed to be used in the TimeAgo tag? Do you pass an opts object as a prop and use relativeDate and mininterval inside it or what? cause that didn't work

**Comment by alanwei0** [comment]
hi @6ichem,

you could use `minInterval` or `relativeDate` like this:

```tsx
<TimeAgo datetime={'2019-11-10'} opts={{ relativeDate: '2019-11-11' }} />
```

and you can find a live example in our [demo](https://git.hust.cc/timeago-react/) page. If it still doesn't work on your env, please provide us more information.
