### ISSUE TITLE
The format is not working

### ISSUE THREAD

**Issue by cassioalmeron** [hustcc/timeago-react#39]
Hellow!

I putted the locale as "pt-BR" (portuguese - Brazil)
![image](https://user-images.githubusercontent.com/50529323/123857963-5a65a800-d8f9-11eb-908b-dd575b52d5e0.png)

But it still printing in English
![image](https://user-images.githubusercontent.com/50529323/123857765-1f637480-d8f9-11eb-88d5-584f03fee105.png)

My default language of my operational system is English - United States

Are some another required thing to to?

Thanks

**Comment by alanwei0** [comment]
@cassioalmeron have you registered pt_BR in advance?

```tsx
import * as React from 'react';
import TimeAgo from 'timeago-react';
import * as timeago from 'timeago.js';

// import it first.
import pt_BR from 'timeago.js/lib/lang/pt_BR';

// register it.
timeago.register('pt_BR', pt_BR);

// then use it.
<TimeAgo
  datetime={'2016-08-08 08:08:08'}
  locale='pt_BR'
/>
```

**Comment by cassioalmeron** [comment]
Its just exactly was missing.

Thanks
