### ISSUE TITLE
React 15.5 deprecations

### ISSUE THREAD

**Issue by szyablitsky** [hustcc/timeago-react#4]
React 15.5 deprecates using `React.PropTypes` and `React.createClass` https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by hustcc** [comment]
Thank you. Can do something to help me by a pr?

**Comment by szyablitsky** [comment]
Sure. I will try and let you know.

**Comment by szyablitsky** [comment]
I updated component to class syntax required by React 15.5.0
It builds with `npm run build`, but I can't start dev server with `npm start`
Also I chnged version to 2.0.0 because this version compatible only with React version >= 15.5
https://github.com/hustcc/timeago-react/pull/5
