### ISSUE TITLE
Time is updated after re-render of the component even if minInterval it's setted to 60

### ISSUE THREAD

**Issue by YagoBiermann** [hustcc/timeago-react#40]
I think that's kind of bug, i'm using simple menu from material-ui and this happen when you click the button and the component get re-rendered. I reproduce this bug on code sandbox, i will put the link below.

![timebug](https://user-images.githubusercontent.com/55931376/132969597-8b08858e-66e1-4097-a5e2-c36b8fc95e9c.gif)

[code sandbox link](https://codesandbox.io/s/timeago-mininterval-bug-sll79?file=/index.js)

**Comment by alanwei0** [comment]
Could you provide me your code snippet about using `<TimeAgo>`?

**Comment by YagoBiermann** [comment]
Of course, i already put it, but here's again: https://codesandbox.io/s/timeago-mininterval-bug-sll79

**Comment by alanwei0** [comment]
@YagoBiermann we did some improvement in the latest version(v3.0.4), you could check the code [here](#41). But we still need you to do some change in your code to fix this issue. In brief, you have to make the props unchanged.

```ts
const timeAgoOpts = { minInterval: 60 }

<TimeAgo opts={timeAgoOpts} datetime={time} />
```

Please let me know if you have any other question.

**Comment by YagoBiermann** [comment]
@alanwei0 now it seems to be working fine, thank you very much for the attention. Have a good day!
