### ISSUE TITLE
Incorrect time ago values

### ISSUE THREAD

**Issue by Morrious** [hustcc/timeago-react#44]
I have been using timeago-react for 6+ months and the value has been accurate as long as I can remember. This morning, I logged into my site and I am seeing "1 day ago" for timestamps on Friday (2-3 days ago). I have refreshed to make sure it wasn't some sort of stale value, but it persists. I created a few components with more recent timestamps and they look to be correct. I am also using the latest release: "timeago-react": "^3.0.4"

![image](https://user-images.githubusercontent.com/32372811/150818532-3648e1b1-7027-460d-ba5b-c83d48f03e96.png)

![image](https://user-images.githubusercontent.com/32372811/150823417-71996eec-8c1c-444f-800e-58b25406706f.png)

```react
<div>
  <TimeAgo datetime={timestamp} className="small text-muted" />
</div>
```

**Comment by Morrious** [comment]
Nevermind, it's too early on a Monday. TimeAgo rounds down to the nearest full day, so it's been more than 1 day, but less than 2 days, so these dates show "1 day ago"

**Comment by alanwei0** [comment]
@Morrious This project is just a react wrapper of [timeago.js](https://github.com/hustcc/timeago.js), if you do care about this logic, you could raise an issue to that repo. Thanks.
