### ISSUE TITLE
why show this type of error on console

### ISSUE THREAD

**Issue by anishkumar127** [hustcc/timeago-react#47]
![image](https://user-images.githubusercontent.com/77631750/202515339-f4f74a92-562a-40db-a7bd-56ea50e78ea0.png)

**Comment by nkilm** [comment]
@anishkumar127 check if you have installed the module at correct location or not.

You should be installing the package in your project's directory where your `package.json` file is present, generally it is kept in root directory.

**Comment by anishkumar127** [comment]
it's was installed in package.json file but don't know why that's was happening. well let it be .i skipped this.
and by the way thanks for reply 🙂
